language: node_js
node_js: stable

sudo: false

addons:
  ssh_known_hosts: git.coding.net

branches:
  only:
  - master

before_install:

install:

# 安装依赖
- npm install hexo-cli -g
- npm install

before_script:

script:

# before_deploy:

deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

# after_deploy:

after_script:

cache:
  apt: true
  directories:
    - node_modules
